defmodule Warui.Repo.TenantMigrations.AddVoidedAtForTransfers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transfers, prefix: prefix()) do
      add :voided_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:transfers, prefix: prefix()) do
      remove :voided_at
    end
  end
end
