defmodule Warui.Repo.TenantMigrations.AddCashflowDomainAndBudgetResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:budgets, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text
      add :description, :text
      add :total_amount, :money_with_currency, null: false
      add :period_start, :date, null: false
      add :period_end, :date, null: false
      add :budget_type, :text, null: false, default: "monthly"
      add :status, :text, null: false, default: "draft"
      add :variance_threshold, :decimal, null: false, default: "0.10"
      add :variance_check_enabled, :boolean, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :budget_owner_id,
          references(:users,
            column: :id,
            name: "budgets_budget_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :budget_ledger_id,
          references(:ledgers,
            column: :id,
            name: "budgets_budget_ledger_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :budget_account_id,
          references(:accounts,
            column: :id,
            name: "budgets_budget_account_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:budgets, "budgets_budget_owner_id_fkey")

    drop constraint(:budgets, "budgets_budget_ledger_id_fkey")

    drop constraint(:budgets, "budgets_budget_account_id_fkey")

    drop table(:budgets, prefix: prefix())
  end
end
