defmodule Warui.Repo.TenantMigrations.AddAssetScaleAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:currencies, prefix: prefix()) do
      add :scale, :bigint, null: false
    end
  end

  def down do
    alter table(:currencies, prefix: prefix()) do
      remove :scale
    end
  end
end
