defmodule Warui.Repo.TenantMigrations.RemoveAllowNilFalseForConstraintsInBudgetResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets, prefix: prefix()) do
      modify :variance_check_enabled, :boolean, null: true, default: true
      modify :variance_threshold, :decimal, null: true
      modify :status, :text, null: true
      modify :budget_type, :text, null: true
    end
  end

  def down do
    alter table(:budgets, prefix: prefix()) do
      modify :budget_type, :text, null: false
      modify :status, :text, null: false
      modify :variance_threshold, :decimal, null: false
      modify :variance_check_enabled, :boolean, null: false, default: nil
    end
  end
end
