defmodule Warui.Repo.TenantMigrations.ChangesToSourceAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:transfers), :user_id, to: :transfer_owner_id

    rename table(:transfers), :ledger_id, to: :transfer_ledger_id

    drop constraint(:transfers, "transfers_ledger_id_fkey")

    drop constraint(:transfers, "transfers_user_id_fkey")

    alter table(:transfers, prefix: prefix()) do
      modify :transfer_owner_id,
             references(:users,
               column: :id,
               name: "transfers_transfer_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :transfer_ledger_id,
             references(:ledgers,
               column: :id,
               name: "transfers_transfer_ledger_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    rename table(:ledgers), :user_id, to: :ledger_owner_id

    drop constraint(:ledgers, "ledgers_user_id_fkey")

    alter table(:ledgers, prefix: prefix()) do
      modify :ledger_owner_id,
             references(:users,
               column: :id,
               name: "ledgers_ledger_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true
    end

    rename table(:accounts), :user_id, to: :account_owner_id

    rename table(:accounts), :ledger_id, to: :account_ledger_id

    drop constraint(:accounts, "accounts_ledger_id_fkey")

    drop constraint(:accounts, "accounts_user_id_fkey")

    alter table(:accounts, prefix: prefix()) do
      modify :account_owner_id,
             references(:users,
               column: :id,
               name: "accounts_account_owner_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :account_ledger_id,
             references(:ledgers,
               column: :id,
               name: "accounts_account_ledger_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end

  def down do
    drop constraint(:accounts, "accounts_account_owner_id_fkey")

    drop constraint(:accounts, "accounts_account_ledger_id_fkey")

    alter table(:accounts, prefix: prefix()) do
      modify :ledger_id,
             references(:ledgers,
               column: :id,
               name: "accounts_ledger_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "accounts_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:accounts), :account_ledger_id, to: :ledger_id

    rename table(:accounts), :account_owner_id, to: :user_id

    drop constraint(:ledgers, "ledgers_ledger_owner_id_fkey")

    alter table(:ledgers, prefix: prefix()) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "ledgers_user_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: false
    end

    rename table(:ledgers), :ledger_owner_id, to: :user_id

    drop constraint(:transfers, "transfers_transfer_owner_id_fkey")

    drop constraint(:transfers, "transfers_transfer_ledger_id_fkey")

    alter table(:transfers, prefix: prefix()) do
      modify :ledger_id,
             references(:ledgers,
               column: :id,
               name: "transfers_ledger_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "transfers_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:transfers), :transfer_ledger_id, to: :ledger_id

    rename table(:transfers), :transfer_owner_id, to: :user_id
  end
end
