defmodule Warui.Repo.TenantMigrations.AddDefaultAccountStatus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts, prefix: prefix()) do
      modify :status, :text, default: "active"
    end
  end

  def down do
    alter table(:accounts, prefix: prefix()) do
      modify :status, :text, default: nil
    end
  end
end
