defmodule Warui.Repo.TenantMigrations.AddGroupPermissionResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_permissions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_permissions_group_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :permission_id,
          references(:permissions,
            column: :id,
            name: "group_permissions_permission_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:group_permissions, [:group_id, :permission_id],
             name: "group_permissions_unique_group_permission_index"
           )
  end

  def down do
    drop_if_exists unique_index(:group_permissions, [:group_id, :permission_id],
                     name: "group_permissions_unique_group_permission_index"
                   )

    drop constraint(:group_permissions, "group_permissions_group_id_fkey")

    drop constraint(:group_permissions, "group_permissions_permission_id_fkey")

    drop table(:group_permissions, prefix: prefix())
  end
end
